--BASS1_SVC_USR_INFO_201410改成表将下面的语句插入
CREATE VIEW BASS1_SVC_USR_INFO_201410 AS
SELECT USER_ID,ACCT_ID,CUST_ID,PHONE_NO,ACTIVE_DATE,PRE_DESTORY_DATE,LAST_TRANS_DATE,BOSS_USER_STATE_ID,
BASS_USER_STATE_ID,BASS1_USER_STATE_ID,CREDIT_LEVEL,CREDIT_OWE,BOSS_USER_TYPE,BASS_USER_TYPE,NOTICE_TYPE,OUTNET_FLAG,DONE_DATE AS DONE_DATE
,OS_STATE,OFFER_ID,BILLING_TYPE,OFFER_ORG_ID,IMSI,CREATE_OP_ID,CREATE_ORG_ID,CREATE_DATE,EXP_DATE,JOIN_DATE,REAL_TYPE,1 as USER_TYPE
 FROM SHDW.DWD_SVC_USR_ALL_INFO_201410
UNION ALL
SELECT USER_ID,ACCT_ID,CUST_ID,PHONE_NO,ACTIVE_DATE,PRE_DESTORY_DATE,LAST_TRANS_DATE,BOSS_USER_STATE_ID,
BASS_USER_STATE_ID,BASS1_USER_STATE_ID,CREDIT_LEVEL,CREDIT_OWE,BOSS_USER_TYPE,BASS_USER_TYPE,NOTICE_TYPE,OUTNET_FLAG,EXP_DATE AS DONE_DATE
,OS_STATE,OFFER_ID,BILLING_TYPE,OFFER_ORG_ID,IMSI,OP_ID,ORG_ID,CREATE_DATE,EXP_DATE,null as CREATE_ORG_ID,null as CREATE_ORG_ID,2 as USER_TYPE
 FROM SHDW.DWD_SVC_USR_INFO_DES_DM_2013
UNION ALL
SELECT USER_ID,ACCT_ID,CUST_ID,PHONE_NO,ACTIVE_DATE,PRE_DESTORY_DATE,LAST_TRANS_DATE,BOSS_USER_STATE_ID,
BASS_USER_STATE_ID,BASS1_USER_STATE_ID,CREDIT_LEVEL,CREDIT_OWE,BOSS_USER_TYPE,BASS_USER_TYPE,NOTICE_TYPE,OUTNET_FLAG,EXP_DATE AS DONE_DATE
,OS_STATE,OFFER_ID,BILLING_TYPE,OFFER_ORG_ID,IMSI,OP_ID,ORG_ID,CREATE_DATE,EXP_DATE,null as CREATE_ORG_ID,null as CREATE_ORG_ID,2 as USER_TYPE
 FROM SHDW.DWD_SVC_USR_INFO_DES_DM_2014 WHERE OP_DATE<DATE('2014-10-01');
--BASS1_SVC_PROD_SERVICE要先写建表语句
DELETE FROM  BASS1_SVC_PROD_SERVICE;
INSERT INTO  BASS1_SVC_PROD_SERVICE
SELECT A.PROD_ID,B.EXTEND_ID AS BOSS_PROD_ID ,A.SERVICE_ID FROM
(
SELECT PROD_ID,SERVICE_ID FROM SHDW.DIM_SVC_PROD
UNION
SELECT PRODUCT_ITEM_ID AS PROD_ID,RELAT_PRODUCT_ITEM_ID AS SERVICE_ID FROM SHODS.ODS_CRM_UP_ITEM_RELAT_20141031  WHERE PROD_ITEM_RELAT_KIND_ID ='SRVC_SINGLE_PRICE_SERVICE'
)A JOIN SHODS.ODS_CRM_UP_PRODUCT_ITEM_201410 B ON A.PROD_ID=B.PRODUCT_ITEM_ID;

CREATE TABLE BASS1_SVC_PROD_INST_201410
(
USER_ID VARCHAR(100),
PROD_ID BIGINT,
SERVICE_ID BIGINT,
BOSS_USER_STATE_ID   SMALLINT,
EFFECTIVE_DATE       TIMESTAMP,
EXPIRE_DATE          TIMESTAMP,
CREATE_DATE          TIMESTAMP
) IN TBSN_APP
PARTITIONING KEY (USER_ID)
NOT  LOGGED  INITIALLY  ;
INSERT INTO BASS1_SVC_PROD_INST_201410
WITH T1(PROD_ID,SERVICE_ID)AS
(
SELECT PROD_ID,SERVICE_ID FROM SHDW.DIM_SVC_PROD
UNION
SELECT PRODUCT_ITEM_ID,RELAT_PRODUCT_ITEM_ID FROM SHODS.ODS_CRM_UP_ITEM_RELAT_20141031 WHERE PROD_ITEM_RELAT_KIND_ID ='SRVC_SINGLE_PRICE_SERVICE'
)
SELECT A.USER_ID,A.PROD_ID,C.SERVICE_ID,B.BOSS_USER_STATE_ID,A.EFFECTIVE_DATE,A.EXPIRE_DATE,A.CREATE_DATE
FROM (SELECT * FROM SHODS.ODS_INS_PROD_201410 WHERE SUBSTR(CHAR(EFFECTIVE_DATE),1,4)||SUBSTR(CHAR(EFFECTIVE_DATE),6,2)<='201410' AND SUBSTR(CHAR(EXPIRE_DATE),1,4)||SUBSTR(CHAR(EXPIRE_DATE),6,2)>'201410') A
JOIN (SELECT USER_ID,BOSS_USER_STATE_ID FROM SHDW.DWD_SVC_USR_ALL_INFO_201410 WHERE BOSS_USER_STATE_ID<>3) B
ON A.USER_ID=B.USER_ID
LEFT JOIN T1 C ON A.PROD_ID=C.PROD_ID;
RUNSTATS  ON TABLE SHFIN.BASS1_SVC_PROD_INST_201410;