--1、补充个人用户确实的数据
INSERT INTO SHDW.DWD_SVC_USR_ALL_INFO_20140923
SELECT B.USER_ID, ACCT_ID, CUST_ID, PHONE_NO, 171000000001,
    ACTIVE_DATE, PRE_DESTORY_DATE, LAST_TRANS_DATE, BOSS_USER_STATE_ID
    , BASS_USER_STATE_ID, BASS1_USER_STATE_ID, CREDIT_LEVEL,
    CREDIT_OWE, ONLINE_TYPE, FREE_CREATE_USER_TYPE, BOSS_USER_TYPE,
    BASS_USER_TYPE, NOTICE_TYPE, OUTNET_FLAG, OS_STATE, OFFER_ID,
    BILLING_TYPE, OFFER_ORG_ID, JOIN_DATE, ONLINE_MONTH,
    ECARD_EXP_DATE, IMSI, REAL_TYPE, CREATE_OP_ID, CREATE_ORG_ID,
    CREATE_DATE, DONE_DATE, EFF_DATE, EXP_DATE  FROM
(
SELECT USER_ID FROM   SHDW.DWD_SVC_USR_INFO_20140923
EXCEPT
SELECT USER_ID FROM   SHDW.DWD_SVC_USR_ALL_INFO_20140923
)A JOIN SHDW.DWD_SVC_USR_INFO_20140923 B ON A.USER_ID=B.USER_ID ;
--2、ODS_MASTER_SUB中状态为4新系统为3
insert into shdw.DWD_SVC_USR_ALL_INFO_20140917 (USER_ID,CUST_ID,phone_no,BOSS_USER_STATE_ID,BASS_USER_STATE_ID,OS_STATE,OFFER_ID,CREATE_DATE,DONE_DATE,EFF_DATE,EXP_DATE,CREDIT_OWE)
with t1(plan_id,offer_id,ROW_NUM) as
(select old_id,new_id,ROW_NUMBER() OVER(PARTITION BY old_id ORDER BY new_id DESC) ROW_NUM from shdw.dim_new_old_relate_map where item_type='OFFER_PLAN')
select b.sub_id,b.acc_id,b.bill_id,3,104,os_status_all,C.offer_ID,b.CREATE_DATE,b.DONE_DATE,b.valid_date,b.expire_date,20140924 from
(select sub_id from  shfin.TEMP_SRVC_BILL_DTL  where plan_id =0
except
select sub_id from  shfin.TEMP_SRVC_BILL_DTL_75  where plan_id =0) a
join shfin.ODS_MASTER_SUB_20140917_75 b on a.sub_id=b.sub_id
join t1 c on b.plan_id=c.plan_id and c.ROW_NUM=1
left join shdw.DWD_SVC_USR_ALL_INFO_20140917 d
on a.sub_id=d.user_id
where d.user_id is null;