select * from ng_evt_busi_rec order by create_time desc;
select * from ng_ins_user where id=10;
select * from ng_ins_offer_main where user_id=10 and STATUS=1;
select * from ng_ins_offer_vas where main_inst_id in (10) and bill_time<now();
select * from ng_ins_offer_vas where main_inst_id = 10 and status='make' and bill_time <now();
select * from ng_up_offer_vas where id=6 order by create_time desc;
select * from ng_up_offer_price_plan where id=39;
select * from ng_customer_booked_apply_detail;
select * from ng_cm_booked_apply_detail;
select * from ng_up_offer_vas where offer_vas_id='901';
select * from ng_ins_offer_main where offer_id='901';
select * from ng_up_price_plan where id=905;
select * from ng_up_offer_price_plan where offer_id='6';
select * from ng_up_offer_rel where offer_id=6;
select * from ng_up_price;
select * from ng_up_plan where id=829;
select * from ng_evt_busi_rec  order by id desc;
select * from ng_ins_user where id=10;
select * from ng_ca_account where id=1;
select * from ng_ca_bill;
select * from ng_ca_pocket;
select * from ng_cm_customer;
select * from ng_ins_user;
select * from ng_ins_offer_main;
select * from ng_ins_offer_vas;
select * from ng_up_offer;
select * from ng_up_offer_price_plan;
select * from ng_up_price_plan;
select * from ng_up_price;
select * from ng_up_plan;
select * from ng_up_offer_item;
select * from ng_up_offer;
select * from ng_up_item;
select * from ng_evt_busi_rec;
select * from ng_evt_busi_rec_line;
select * from ng_ca_pocket;
select * from ng_ca_pocket_chg;
select * from ng_up_offer_main;
select * from ng_up_offer_vas;
select * from ng_up_offer_rel;
select * from ng_up_service;
select * from ng_up_product;