CREATE TABLE DIM_BASS1_CHANNEL_STATIC_DATA
(
  CHANNEL_ID             BIGINT,
  HOUR24_FLAG            VARCHAR(25),
  COUNTY_NAME            VARCHAR(30),
  TOWN_NAME              VARCHAR(50),
  CHANNEL_NAME           VARCHAR(100),
  CHANNEL_ADDRESS        VARCHAR(100),
  CHANNEL_MANAGE_NAME    VARCHAR(40),
  CHANNEL_MANAGE_MOBILE  VARCHAR(40),
  CHANNEL_PHONE          VARCHAR(40),
  LOCATION_TYPE          VARCHAR(1),
  AREA_TYPE              VARCHAR(1),
  NO_OTHER               VARCHAR(1),
  IS_SELL_MOBILE_FLAG    VARCHAR(1),
  FLAG_DDQH              VARCHAR(1),
  FLAG_VIP               VARCHAR(1),
  FLAG_TERM              VARCHAR(1),
  FLAG_KQ                VARCHAR(1),
  CHANNEL_LEVEL          VARCHAR(1),
  CHANNEL_STATUS         VARCHAR(1),
  START_TIME             VARCHAR(4),
  END_TIME               VARCHAR(4),
  VALID_DATE             VARCHAR(8),
  EXPIRE_DATE            VARCHAR(8),
  OP_MONTH               SMALLINT,
  LATITUDE               VARCHAR(10),
  MAGNITUTE              VARCHAR(10),
  DECO_FEE               BIGINT,
  DEVICE_FEE             BIGINT,
  OFFICE_FEE             BIGINT,
  PENSION                BIGINT,
  SUPPLIER_TYPE          VARCHAR(1),
  PURCHASE_MONTH         VARCHAR(6),
  BUILDING_CERT_NO       VARCHAR(50),
  LAND_CERT_NO           VARCHAR(50),
  IC_NO                  VARCHAR(50),
  PRICE                  BIGINT,
  RENT_START_DATE        VARCHAR(8),
  RENT_END_DATE          VARCHAR(8),
  AVERAGE_RENT           BIGINT,
  BUILDING_AREA          INTEGER,
  USEABLE_AREA           INTEGER,
  FRONTER_AREA           INTEGER,
  COUNTER_NUM            SMALLINT,
  STAFF_NUM              SMALLINT,
  SEC_NUM                SMALLINT,
  CLEANER_NUM            SMALLINT,
  QUERY_FLAG             VARCHAR(1),
  POS_FLAG               VARCHAR(1),
  VIP_COUNTER_FLAG       VARCHAR(1),
  VIP_ROOM_FLAG          VARCHAR(1),
  PRINTER_NUM            SMALLINT,
  TERM_NUM               SMALLINT,
  G3_AREA                INTEGER,
  TV_NUM                 SMALLINT,
  NEWBUSI_PLAT_NUM       SMALLINT,
  G3_TERM_NUM            SMALLINT,
  NET_TERM_NUM           SMALLINT,
  AREA                   INTEGER,
  SERVICE_AREA           INTEGER,
  NET_TYPE               VARCHAR(1),
  AIR_CHARGE_FLAG        VARCHAR(1)
 )
DATA CAPTURE NONE
IN TBSN_DW
PARTITIONING KEY
 (CHANNEL_ID
 ) USING HASHING;
INSERT INTO DIM_BASS1_CHANNEL_STATIC_DATA
SELECT A.CHANNEL_ID,A.HOUR24_FLAG,A.COUNTY_NAME,A.TOWN_NAME,A.CHANNEL_NAME,A.CHANNEL_ADDRESS,A.CHANNEL_MANAGE_NAME,
 A.CHANNEL_MANAGE_MOBILE,A.CHANNEL_PHONE,A.LOCATION_TYPE,A.AREA_TYPE,A.NO_OTHER,A.IS_SELL_MOBILE_FLAG,A.FLAG_DDQH,
 A.FLAG_VIP,A.FLAG_TERM,A.FLAG_KQ,A.CHANNEL_LEVEL,A.CHANNEL_STATUS,A.START_TIME,A.END_TIME,A.VALID_DATE,A.EXPIRE_DATE,A.OP_MONTH,A.LATITUDE,A.MAGNITUTE,
 A.DECO_FEE,A.DEVICE_FEE,A.OFFICE_FEE,A.PENSION,B.SUPPLIER_TYPE,B.PURCHASE_MONTH,B.BUILDING_CERT_NO,B.LAND_CERT_NO,B.IC_NO,
 B.PRICE,B.RENT_START_DATE,B.RENT_END_DATE,B.AVERAGE_RENT,C.BUILDING_AREA,C.USEABLE_AREA,C.FRONTER_AREA,C.COUNTER_NUM,C.STAFF_NUM,
 C.SEC_NUM,C.CLEANER_NUM,C.QUERY_FLAG,C.POS_FLAG,C.VIP_COUNTER_FLAG,C.VIP_ROOM_FLAG,C.PRINTER_NUM,C.TERM_NUM,C.G3_AREA,C.TV_NUM,
 C.NEWBUSI_PLAT_NUM,C.G3_TERM_NUM,C.NET_TERM_NUM,C.AREA,C.SERVICE_AREA,C.NET_TYPE,C.AIR_CHARGE_FLAG
 FROM SHBASS.BASS1_06035_CHANNEL_INFO_LOCAL_20150527_75 A
LEFT JOIN SHBASS.BASS1_06036_CHANNEL_RENT_20150527_75 B
ON A.CHANNEL_ID=B.CHANNEL_ID
LEFT JOIN SHBASS.BASS1_06037_CHANNEL_RESOURCE_20150527_75 C
ON A.CHANNEL_ID=C.CHANNEL_ID;
RUNSTATS ON TABLE SHBASS.DIM_BASS1_CHANNEL_STATIC_DATA;

update SHBASS.BASS1_CHANNEL_INFO_BASE_20150518 a
 set (IS_SELL_MOBILE_FLAG,SUPPLIER_TYPE) =
  (select case when a.IS_SELL_MOBILE_FLAG is not null then a.IS_SELL_MOBILE_FLAG else b.IS_SELL_MOBILE_FLAG end as IS_SELL_MOBILE_FLAG,
        case when a.SUPPLIER_TYPE is not null then a.SUPPLIER_TYPE else b.SUPPLIER_TYPE end  as SUPPLIER_TYPE from SHBASS.DIM_BASS1_CHANNEL_STATIC_DATA b where  a.CHANNEL_ID=b.CHANNEL_ID);




