---检查数据量 目标表25420442  源表25420442
select  count(1)  from SHDW.DWD_ACC_BUSI_REC_EXT_201311;
select  count(1)  from SHODS.ODS_CA_BUSI_REC_EXT_201311;
---检查主要字段
select SO_NBR, SO_DATE, ACCT_ID, AMOUNT, PRE_BALANCE,
    BALANCE, CARD_SERIAL_NO, BANK_ID, BILLING_TYPE
  from SHDW.DWD_ACC_BUSI_REC_EXT_201311;
SELECT  SO_NBR,SO_DATE,ACCT_ID,AMOUNT,PRE_BALANCE,BALANCE
       ,CARD_SERIAL_NO,BANK_ID,BILLING_TYPE
  from SHODS.ODS_CA_BUSI_REC_EXT_201311;

