--创建表
create table DWD_ACC_PREPAY_SPLITED_201401 like SHTEMPLATE.DWD_ACC_PREPAY_SPLITED_YYYYMM;
--先插入非当月预收分摊的记录
INSERT INTO DWD_ACC_PREPAY_SPLITED_201401
select A.BILL_CODE,A.ACC_ID,A.SUB_ID,A.ACC_CODE,A.ACC_FEE,0 ACC_FEE,0,0,A.BILL_MONTH
from DB2INFO.DW_SRVC_BILL_DTL_PREPAY_SPLIT_201401 A where bill_month<>'201401';
--将帐户用户科目费用进行累加以防止重复
create table DW_SRVC_BILL_DTL_201401_FEE like DB2INFO.DW_SRVC_BILL_DTL_201401;
insert into  DW_SRVC_BILL_DTL_201401_FEE(bill_code,sub_id,acc_code,acc_fee)
select SUBSTR(BILL_CODE,1,11),sub_id,acc_code,sum(acc_fee) from DB2INFO.DW_SRVC_BILL_DTL_201401 group by SUBSTR(BILL_CODE,1,11),sub_id,acc_code;
--将同一账户，同一用户，同一科目的费用重复的进行累加
create table DWD_ACC_PREPAY_SPLITED_201401_FEE like DWD_ACC_PREPAY_SPLITED_201401;
insert into DWD_ACC_PREPAY_SPLITED_201401_FEE(BILL_NO,ACCT_ID,USER_ID,ITEM_CODE,AFTER_SPLIT_FEE)
select BILL_CODE,ACC_ID,SUB_ID,ACC_CODE,SUM(ACC_FEE) from DB2INFO.DW_SRVC_BILL_DTL_PREPAY_SPLIT_201401 where bill_month='201401'
group by BILL_CODE,ACC_ID,SUB_ID,ACC_CODE WITH UR;
--补当月预收分摊记录及账单费用
INSERT INTO DWD_ACC_PREPAY_SPLITED_201401
SELECT A.BILL_NO,A.ACCT_ID,A.USER_ID,A.ITEM_CODE,A.AFTER_SPLIT_FEE,VALUE(B.ACC_FEE,0),0,0,201401
  FROM DWD_ACC_PREPAY_SPLITED_201401_FEE A LEFT JOIN DW_SRVC_BILL_DTL_201401_FEE  B
  ON A.ACCT_ID=B.BILL_CODE AND A.USER_ID=B.SUB_ID AND A.ITEM_CODE=B.ACC_CODE WITH UR;