---检查数据量 目标表14185
select count(1)
  from SHDW.DIM_ACC_WMS_NAVTREEMAP;
select count(1) from
(
select LVL1GROUP, '1' as REASON_LEVEL, LVL1DESC
  from SHODS.ODS_DB_WMS_NAVTREEMAP_20131231
 where LENGTH(LVL1GROUP) > 0
   and TREEINDEX IN ('TSGDM', 'BZGDM')
union
select LVL2GROUP, '2' as REASON_LEVEL, LVL2DESC
  from SHODS.ODS_DB_WMS_NAVTREEMAP_20131231
 where LENGTH(LVL2GROUP) > 0
   and TREEINDEX IN ('TSGDM', 'BZGDM')
union
select LVL3GROUP, '3' as REASON_LEVEL, LVL3DESC
  from SHODS.ODS_DB_WMS_NAVTREEMAP_20131231
 where LENGTH(LVL3GROUP) > 0
   and TREEINDEX IN ('TSGDM', 'BZGDM')
union
select LVL4GROUP, '4' as REASON_LEVEL, LVL4DESC
  from SHODS.ODS_DB_WMS_NAVTREEMAP_20131231
 where LENGTH(LVL4GROUP) > 0
   and TREEINDEX IN ('TSGDM', 'BZGDM')
union
select LVL5GROUP, '5' as REASON_LEVEL, LVL5DESC
  from SHODS.ODS_DB_WMS_NAVTREEMAP_20131231
 where LENGTH(LVL5GROUP) > 0
   and TREEINDEX IN ('TSGDM', 'BZGDM')
)G
---检查主要字段
select REASON_CODE, REASON_NAME, REASON_LEVEL
  from SHDW.DIM_ACC_WMS_NAVTREEMAP;


