INSERT INTO SHDW.DWA_FIN_ACCT_BILL_201404
SELECT BILL_CODE,ACC_ID,BILL_MONTH,OLD_TOTAL_FEE,UNPAY_AMT,ODDMENT_AMT,BILL_STATUS,PAY_TYPE FROM "SHODS"."ODS_ACCT_BILL_201404";

runstats on table  SHDW.DWA_FIN_ACCT_BILL_201404  with distribution and detailed indexes all;