select ACCT_ID, USER_ID, BILL_MONTH, BILL_NO, ITEM_CODE, PROD_ID, 
    BILL_TOTAL
  from SHDW.DWD_ACC_PREPAY_SPLIT_201311;
  select count(1)
  from SHDW.DWD_ACC_PREPAY_SPLIT_201311;
 select ACC_ID, SUB_ID, BILL_MONTH, BILL_CODE, ACC_CODE, PRODUCT_ID
    , SERVICE_ID, BILL_TOTAL, MONTH_NUM, BEGIN_DATE, END_DATE, 
    SPLIT_TYPE, SPLIT_RATE, SPLIT_TOTAL, TRANS_TOTAL, SUCC_MONTH, 
    DONE_CODE, STATUS, NOTES, CREATE_DATE, OPR_ID, ORG_ID, EXT1,
    EXT2, EXT3, EXT4, EXT5
  from SHODS.ODS_GROUP_PREPAY_SPLIT_201311;
 select count(1)
  from SHODS.ODS_GROUP_PREPAY_SPLIT_201311;
SELECT           ACC_ID
                ,SUB_ID
                ,BILL_MONTH
                ,BILL_CODE
                ,ACC_CODE
                ,PRODUCT_ID
                ,BILL_TOTAL*1.0/100
          SHODS.ODS_GROUP_PREPAY_SPLIT_201311;