CREATE TABLE DB2INFO.TEMP_ODS_CA_BILL_201406
 (BILL_NO              BIGINT,
  ACCT_ID              VARCHAR(20),
  RESOURCE_ID          VARCHAR(21),
  DEFAULT_ACCT_ID      BIGINT,
  REGION_CODE          SMALLINT,
  BILL_FEE             BIGINT,
  PPY_FEE              BIGINT,
  UNPAY_FEE            BIGINT,
  DELAY_LATE_FEE       BIGINT,
  MEASURE_ID           INTEGER,
  BILL_MONTH           INTEGER,
  CREATE_DATE          TIMESTAMP,
  BEGIN_DATE           TIMESTAMP,
  END_DATE             TIMESTAMP,
  STS                  SMALLINT,
  STS_DATE             TIMESTAMP,
  BILLING_TYPE         SMALLINT,
  SRC_NO               VARCHAR(64),
  DUE_DATE             TIMESTAMP,
  CREDIT_SIGN_CONTROL  SMALLINT
 )
  DATA CAPTURE NONE
 IN TBS_ODS_YZ_MONTH
 INDEX IN TBS_INDEX
  PARTITIONING KEY
   (BILL_NO
   ) USING HASHING;

insert into DB2INFO.TEMP_ODS_CA_BILL_201406 select * from DB2INFO.ODS_CA_BILL_201406;

runstats on table  DB2INFO.TEMP_ODS_CA_BILL_201406  with distribution and detailed indexes all;

create table DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406_20140702_BAK  LIKE DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406;

insert into DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406_20140702_BAK select * from DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406;

runstats on table  DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406_20140702_BAK  with distribution and detailed indexes all;

ALTER TABLE DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406 ACTIVATE NOT LOGGED INITIALLY WITH EMPTY TABLE;

insert into DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406 select B.ACCT_ID||'1406', A.SUB_ID, ACC_CODE, ADJUST_NO, TOTAL_FEE, PRE_FEE,
    UNPAY_AMT, TOTAL_UNIT, TOTAL_CNT, CELL_COUNT, HAS_LATE_FEE,
    TAX_RATE, TAX_FEE
  from DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406_BAK A  LEFT JOIN DB2INFO.TEMP_ODS_CA_BILL_201406  B ON A.BILL_NO=B.BILL_NO;

runstats on table  DB2INFO.ODS_SRVC_BILL_DTL_FOUR_201406  with distribution and detailed indexes all;