--检查数据量
select count(1)
  from SHDW.DWD_ACC_ADJUST_INFO_201311
except
select count(1) from shods.ODS_CA_ADJUST_INFO_201311;
--检查关键字段差异
select   so_nbr,ACCT_ID,REASON_ONE,REASON_TWO,REASON_THREE,REASON_FOUR,REASON_FIVE,DEPT_CODE,DEAL_REASON,ADJUST_JF_REASON
  from "SHDW"."DWD_ACC_ADJUST_INFO_201311"
except
select so_nbr,ACCT_ID,REASON_ONE,REASON_TWO,REASON_THREE,REASON_FOUR,REASON_FIVE,
      DEPT_CODE,DEAL_REASON,ADJUST_JF_REASON from shods.ODS_CA_ADJUST_INFO_201311;

