select curdutyer from md.proc where proc_name = 'DwdEvtCallUsrD'

INSERT INTO {BASS1DWD}.BASS1_USER_SRVC_&TASK_ID
  WITH T3 AS
  (
  SELECT B.AGENT_ID,A.CHANNEL_ENTITY_ID
  FROM (SELECT CHANNEL_ENTITY_ID,
               PARENT_ENTITY AS AGENT_ID,
               ROW_NUMBER() OVER(PARTITION BY PARENT_ENTITY ORDER BY DONE_DATE DESC) AS SEQ_NO
          FROM {ODS}.ODS_CHANNEL_ENTITY_REL_INFO_NEW_&TASK_ID
         WHERE REC_STATUS = 1) A
  JOIN {BASS1DWD}.BASS1_06035_CHANNEL_INFO_&TASK_ID B
    ON A.CHANNEL_ENTITY_ID = B.CHANNEL_ID
 WHERE SEQ_NO = 1
  ),T1 AS
   (SELECT A.USER_ID,
           A.CUST_ID,
           '1' AS USER_TYPE,
           A.JOIN_DATE,
           '01' AS USER_BUSITYPE_ID,
           A.PHONE_NO,
           A.IMSI,
           '10200' AS CMCC_ID,
           CASE
             WHEN C.AGENT_ID IS NOT NULL THEN
               CHAR(C.AGENT_ID)
             WHEN F.CHANNEL_ID IS NOT NULL THEN
               CHAR(F.CHANNEL_ID)
             WHEN G.CHANNEL_ENTITY_ID IS NOT NULL THEN
               CHAR(G.CHANNEL_ENTITY_ID)
             WHEN D.BASS1_CHL IS NOT NULL THEN
               D.BASS1_CHL
             WHEN E.BASS1_CHL IS NOT NULL THEN
               E.BASS1_CHL
             ELSE
              'BASS1_UM'
           END AS CHANNEL_ID,
           2 AS MOBILE_PUB_TYPE,
           A.BILLING_TYPE,
           '04' AS ENTER_TYPE,
           A.OFFER_ID,
           A.BASS_USER_STATE_ID
      FROM {DWD}.DWD_SVC_USR_ALL_INFO_&TASK_ID A
      LEFT JOIN {DWA}.DWA_RES_SALE_ACTIVE_&TASK_ID B
        ON A.USER_ID = B.USER_ID
      LEFT JOIN {ODS}.ODS_CHANNEL_ORG_AGENT_NEW_&TASK_ID C
        ON B.ORG_AGENT_ID = C.ORG_ID
      LEFT JOIN {BASS1DWD}.BASS1_06035_CHANNEL_INFO_&TASK_ID F
        ON B.ORG_AGENT_ID=F.CHANNEL_ID
      LEFT JOIN T3 G
        ON B.ORG_AGENT_ID=G.AGENT_ID
      LEFT JOIN {BASS1DWD}.DIM_BASS1_CHANNEL_OP_INFO_&TASK_ID D
        ON B.OP_ID = D.OP_ID
      LEFT JOIN {BASS1DWD}.DIM_BASS1_CHANNEL_OP_INFO_&TASK_ID E
        ON B.ORG_ID = E.ORG_ID
     WHERE A.BASS_USER_STATE_ID <> '103'),
  T2 AS
   (SELECT OFFER_ID,
           BASS1_VALUE1 AS BASS1_BRAND_ID,
           BASS1_VALUE2 AS BASS1_DATA_CARD_M2M_TYPE
      FROM SHBASS.BASS1_MAP_PLAN
     WHERE BASS1_VALUE1 IN (1, 2, 3))
  SELECT T1.USER_ID,
         T1.CUST_ID,
         T1.USER_TYPE,
         CASE WHEN E.CREATE_DATE IS NOT NULL THEN E.CREATE_DATE ELSE T1.JOIN_DATE END,
         T1.USER_BUSITYPE_ID,
         T1.PHONE_NO,
         T1.IMSI,
         T1.CMCC_ID,
         CASE
           WHEN E.CHANNEL_ID IS NOT NULL THEN
             E.CHANNEL_ID
           WHEN T1.CHANNEL_ID IS NOT NULL THEN
            CHAR(T1.CHANNEL_ID)
           ELSE
            'BASS1_UM'
         END,
         T1.MOBILE_PUB_TYPE,
         T1.BILLING_TYPE,
         T1.ENTER_TYPE,
         T2.BASS1_BRAND_ID,
         T2.BASS1_DATA_CARD_M2M_TYPE,
         0,
         T1.BASS_USER_STATE_ID
    FROM T1
    JOIN T2
      ON T1.OFFER_ID = T2.OFFER_ID
    LEFT JOIN {DWD}.DWD_SVC_USR_TESTCARD_&TASK_ID D
      ON T1.PHONE_NO = D.PHONE_NO
    LEFT JOIN {BASS1DWD}.BASS1_USER_SRVC_&PDTASK_ID E
      ON T1.USER_ID=E.SUB_ID
   WHERE D.PHONE_NO IS NULL