--db2调试通过代码
SELECT DISTINCT I.PROD_ID,F.FREERES_ITEM,G.START_VALUE,G.END_VALUE,
CASE WHEN H.MEASURE_ID IN (106,109) THEN G.AMOUNT ELSE
CASE WHEN H.MEASURE_ID=102 THEN G.AMOUNT/60 ELSE
CASE WHEN H.MEASURE_ID=103 THEN G.AMOUNT/(1024*1024) END END END AS AMOUNT
,CASE WHEN H.MEASURE_ID IN (106,109) THEN H.MEASURE_ID ELSE
CASE WHEN H.MEASURE_ID=102 THEN 106 ELSE
CASE WHEN H.MEASURE_ID=103 THEN 105 END END END AS  MEASURE_ID
FROM SHODS.ODS_PM_PRODUCT_OFFERING_20140515 A
JOIN (SELECT DISTINCT PRODUCT_OFFERING_ID,PRICING_PLAN_ID FROM SHODS.ODS_PM_PRODUCT_PRICING_PLAN_20140515 ) B ON A.PRODUCT_OFFERING_ID=B.PRODUCT_OFFERING_ID
JOIN (SELECT C.PRICING_PLAN_ID,C.PRICE_ID,C.BILLING_TYPE,D.TAX_INCLUDED FROM SHODS.ODS_PM_COMPOSITE_OFFER_PRICE_20140515 C,SHODS.ODS_PM_COMPONENT_PRODOFFER_PRICE_20140515 D
WHERE C.PRICE_ID=D.PRICE_ID AND D.PRICE_TYPE IN (3,4) )E
ON B.PRICING_PLAN_ID=E.PRICING_PLAN_ID
JOIN SHODS.ODS_PM_ALLOWANCE_FREERES_DETAILS_20140515 F
ON E.PRICE_ID=F.PRICE_ID
JOIN SHODS.ODS_PM_ALLOWANCE_FREERES_SEGMENT_20140515 G
ON F.PRICE_ID=G.PRICE_ID
JOIN SHODS.ODS_PM_FREE_USAGE_PROPERTY H
ON F.FREERES_ITEM=H.ASSET_ITEM_ID
JOIN SHDW.DIM_ACC_BOSSPROD_CRMPROD_REL I
ON A.PRODUCT_OFFERING_ID=I.BOSS_PROD_ID  WITH UR;

SELECT distinct A.PRODUCT_OFFERING_ID,
       A.NAME,
       F.FREERES_ITEM,
       L.NAME,
       F.CYCLE_REF_MODE,
       G.START_VALUE,
       G.END_VALUE,
       G.AMOUNT,
       G.LIMIT_AMOUNT,
       H.MEASURE_ID
  FROM PD.PM_PRODUCT_OFFERING          A,
       PD.PM_PRODUCT_PRICING_PLAN      B,
        PD.PM_PRICING_PLAN             C,
       PD.PM_COMPOSITE_OFFER_PRICE     D,
       PD.PM_COMPONENT_PRODOFFER_PRICE E,
       PD.PM_ALLOWANCE_FREERES_DETAILS F,
       PD.PM_ALLOWANCE_FREERES_SEGMENT G,
       PD.pm_asset_item               L,
       PD.PM_FREE_USAGE_PROPERTY       H
 WHERE A.PRODUCT_OFFERING_ID = B.PRODUCT_OFFERING_ID
   AND B.PRICING_PLAN_ID = C.PRICING_PLAN_ID
   AND C.PRICING_PLAN_ID = D.PRICING_PLAN_ID
   AND D.PRICE_ID = E.PRICE_ID
   AND E.PRICE_TYPE IN (3,4)
   AND E.PRICE_ID = F.PRICE_ID
   AND E.PRICE_ID = G.PRICE_ID
   AND F.FREERES_ITEM=L.Asset_Item_Id
   AND F.FREERES_ITEM=H.ASSET_ITEM_ID(+)

   1946011


