CREATE TABLE TEMPLATE.DWD_ACC_ITEM_OWE
 (ACCT_ID        VARCHAR(20),
  ITEM_CODE      INTEGER,
  BILL_MONTH     INTEGER,
  UNPAY_FEE      DECIMAL(20, 2),
  PROD_INST_ID   BIGINT,
  PAY_STS        INTEGER,
  BILL_STS       INTEGER,
  OWE_DATE       DATE,
  PAY_TYPE       INTEGER,
  STAT_DATE      DATE,
  DATA_TIME      INTEGER
 )